---
# Defines deployment design and assigns role to server groups

## NVMesh Management Role
- hosts: nvmesh_management
  gather_facts: true
  become: True
  any_errors_fatal: true

  tasks:
    - import_role:
        name: nvmesh-management


## NVMesh Client Role
- hosts: nvmesh_client
  gather_facts: true
  become: True

  tasks:
    - import_role:
        name: nvmesh-client


## NVMesh Target Role
- hosts: nvmesh_target
  gather_facts: true
  become: True

  tasks:
    - import_role:
        name: nvmesh-target