---
# Defines deployment design and assigns role to server groups

- hosts:
  - nvmesh_management
  - nvmesh_target
  - nvmesh_client

  any_errors_fatal: true
  become: true

  tags: always

  vars:
    delegate_facts_host: True

# - hosts: nvmesh_management
#   gather_facts: true
#   become: True
#   any_errors_fatal: true
#   pre_tasks:
#     - name: set nvmesh-management install 'In Progress'
#       run_once: true
#       set_stats:
#         data:
#           installer_phase_excelero_mgr:
#             status: "In Progress"
#             start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

#   tasks:
#     - import_role:
#         name: nvmesh-management


#   post_tasks:
#     - name: set nvmesh-management install 'Complete'
#       run_once: true
#       set_stats:
#         data:
#           installer_phase_excelero_mgr:
#             status: "Complete"
#             end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

- hosts: nvmesh_client
  gather_facts: true
  become: True

  tasks:
    - import_role:
        name: nvmesh-client
