---
# Defines deployment design and assigns role to server groups

- hosts:
  - nvmesh-management
  - nvmesh-target
  - nvmesh-client

  any_errors_fatal: true
  become: true

  tags: always

  vars:
    delegate_facts_host: True

- hosts: nvmesh-management
  gather_facts: true
  become: True
  any_errors_fatal: true
  pre_tasks:
    - name: set nvmesh-management install 'In Progress'
      run_once: true
      set_stats:
        data:
          installer_phase_excelero_mgr:
            status: "In Progress"
            start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

  tasks:
    - import_role:
        name: nvmesh-management


  post_tasks:
    - name: set nvmesh-management install 'Complete'
      run_once: true
      set_stats:
        data:
          installer_phase_excelero_mgr:
            status: "Complete"
            end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

#- hosts: excelero_nodes
#  gather_facts: true
#  become: True
#
#  tasks:
#    - import_role:
#       name: excelero-common
#    - import_role:
#       name: excelero-node
#    - import_role:
#       name: beegfs-common
#    - import_role:
#       name: beegfs-node
