---

- name: Verify Linux distribution and version
  assert:
    that:  
    - ansible_distribution is match desired_distribution and ansible_distribution_version is version desired_distribution_version
    fail_msg: Installed distribution {{ ansible_distribution }} {{ ansible_distribution_version }} does not match {{ desired_distribution }} {{ desired_distribution_version }}
    success_msg: Installed distribution is {{ ansible_distribution }} {{ ansible_distribution_version }}

- name: Verify current Linux kernel version
  assert:
    that:
    - ansible_kernel is match desired_kernel
    fail_msg: Installed kernel {{ ansible_kernel }} does not match {{ desired_kernel }}
    success_msg: Installed kernel is {{ ansible_kernel }}

- name: Test whether SELinux is enabled
  command: /usr/sbin/selinuxenabled
  ignore_errors: yes
  changed_when: False
  register: selinux_status

- name: Verify that SELinux is disabled
  assert:
    that: 
    - selinux_status.rc != 0
    fail_msg: SELinux is enabled
    success_msg: SELinux is disabled

## Future -- if SELinux is enabled, configure services and modules to work with it successfully.
