##### Reference for setting variables or inventory (NOTE: INI format requires "=" and not ":")
##### The following are required for nvmesh-management, nvmesh-client, and nvmesh-target roles;
##### and are defined in the respective group_vars/<group_name>.yml
#####   nvmesh_repo_release, nvmesh_repo_distribution, nvmesh_repo_username, nvmesh_repo_password
##### These are additionally required for the pre-checks used in nvmesh-client and nvmesh-target;
##### and are also defined in the respective group_vars/<group_name>.yml 
#####   desired_distribution, desired_distribution_version, desired_kernel

# nvmesh_repo_release: 2.2        # e.g. for 2.2.0
# nvmesh_repo_release: 2.0        # e.g. for 2.0.5
# nvmesh_repo_username: someuser
# nvmesh_repo_password: password

##### For CentOS
# desired_distribution: CentOS
# nvmesh_repo_distribution: centos

##### For RHEL
# desired_distribution: RedHat
# nvmesh_repo_distribution: redhat

##### Distribution version and kernel are common for CentOS and RHEL  The following example has a 2.0.5- and 2.2-compatible kernel
##### Always refer to the Interoperability Matrix to ensure that the entered desired versions are aligned and supported.

# desired_distribution_version: 8.2                               # Because this matches an ansible fact, do not use 8.2.2004
# desired_kernel: 4.18.0-193.19.1.el8_2.x86_64


##### Future: add Ubuntu