##### Reference for setting variables in inventory (NOTE: INI format requires "=" and not ":")
##### Ensure that each of the following is defined in inventory:
#####   nvmesh_repo_release, nvmesh_repo_distribution, nvmesh_repo_username, nvmesh_repo_password
#####   desired_distribution, desired_distribution_version, desired_kernel

# nvmesh_repo_release: 2.0
# nvmesh_repo_username: someuser
# nvmesh_repo_password: password

##### For CentOS
# desired_distribution: CentOS
# nvmesh_repo_distribution: centos

##### For RHEL
# desired_distribution: RedHat
# nvmesh_repo_distribution: redhat

##### Distribution version and kernel are common for CentOS and RHEL

# desired_distribution_version: 8.2
# desired_kernel: 4.18.0-193.el8.x86_64
# desired_kernel: 4.18.0-193.6.3.el8_2.x86_64
# desired_kernel: 4.18.0-193.13.2.el8_2.x86_64
# desired_kernel: 4.18.0-193.14.3.el8_2.x86_64
# desired_kernel: 4.18.0-193.19.1.el8_2.x86_64

# desired_distribution_version: 8.1
# desired_kernel: 4.18.0-147.el8.x86_64
# desired_kernel: 4.18.0-147.8.1.el8_1.x86_64

# desired_distribution_version: 7.9
# desired_kernel: 3.10.0-1160.el7.x86_64

# desired_distribution_version: 7.8
# desired_kernel: 3.10.0-1127.el7.x86_64
# desired_kernel: 3.10.0-1127.8.2.el7.x86_64
# desired_kernel: 3.10.0-1127.10.1.el7.x86_64
# desired_kernel: 3.10.0-1127.13.1.el7.x86_64
# desired_kernel: 3.10.0-1127.18.2.el7.x86_64

# desired_distribution_version: 7.7
# desired_kernel: 3.10.0-1062.el7.x86_64
# desired_kernel: 3.10.0-1062.9.1.el7.x86_64
# desired_kernel: 3.10.0-1062.12.1.el7.x86_64
# desired_kernel: 3.10.0-1062.18.1.el7.x86_64



##### Future: add Ubuntu