---

- name: Verify that Configured Network Interfaces are Active
  assert:
    that:
    - "hostvars[inventory_hostname]['ansible_' + item.interface]['active']"
    fail_msg: "{{ item.interface }} of type {{ hostvars[inventory_hostname]['ansible_' + item.interface]['type'] }} is not active"
    success_msg: "{{ item.interface }} of type {{ hostvars[inventory_hostname]['ansible_' + item.interface]['type'] }} is active"
  loop: "{{ nvmesh_configured_nics | dict2items(key_name='interface', value_name='protocol') }}"

- name: Build CONFIGURED_NICS string
  set_fact:
    nvmesh_configured_nics_string: "{{ nvmesh_configured_nics_string }}{{ (index > 0)|ternary(';','') }}{{ item.interface }}/{{ item.protocol }}"
  loop: "{{ nvmesh_configured_nics | dict2items(key_name='interface', value_name='protocol') }}"
  loop_control:
    index_var: index

- name: Debug CONFIGURED_NICS string
  debug:
    var: nvmesh_configured_nics_string

## TODO: template or direct file manipulation to inject full CONFIGURED_NICS 
##       need to figure out the quoting when doing that