---

- include_tasks: configure-firewalld.yml
- include_tasks: install-nvmesh-packages.yml
- include_tasks: set-tuned-adm.yml
- include_tasks: populate-nvmesh-conf.yml
- include_tasks: set-sysctl-params.yml
